repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest stable version
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
        types_or: [cuda, proto, textproto, python]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
        args: ['--verbose', '--redact', '--no-banner']
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo check
        entry: cargo check --all-targets
        language: system
        files: \.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
